### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by dgrmunch** [alda-lang/web-demo#3]
Ey bud, I get an error in the demo:

https://alda-lang.github.io/web-demo/#piano: a c c

Does the project still work?

**Comment by daveyarwood** [comment]
The web demo is not actively maintained, although I'm happy to manage contributions if someone is interested in working on it.

It uses a very old version of the Alda parser which was based on a BNF grammar -- things work way differently now. I think to do things properly, we would want to convert alda-core (a Clojure library) to [cljc](https://github.com/clojure/clojurescript/wiki/Using-cljc) so that we could target both Java at the command-line and JavaScript in the browser. That way, we could easily keep the ClojureScript version up-to-date instead of having to manage it as a separate library and manually update it each time the Clojure version changes.

I took a brief look, and it looks like the web demo has stopped working because the sound font files loaded by the MIDI.js library are no longer accessible. I saw in the JS console that there was a 404 trying to access https://raw.githubusercontent.com/gleitz/midi-js-soundfonts/master/FluidR3_GM/acoustic_grand_piano-ogg.js.

**Comment by ondras** [comment]
I fixed the incorrect instrument path, but this is indeed only a quick'n'dirty change. The underlying Alda library is still a ~2 years old build.

**Comment by daveyarwood** [comment]
That got it working -- thanks for the quick fix, @ondras!

**Comment by dgrmunch** [comment]
Thanks guys! :) Cool to play with
Hope this project continues :)

[image: SciArt Lab] <http://www.sciartlab.com/>

Diego González, PhD | Research & Development

xmunch@xmunch.com

*Personal website*: http://www.xmunch.com

*SciArt Lab*:  http://www.sciartlab.com




This e-mail message may contain confidential or legally privileged
information and is intended only for the use of the intended recipient(s).
If you want to encrypt our communications we can use cryptographic tools.
You can find my PGP public key here: http://xmunch.com/pgp.
